"""initial schema — trades (partitioned) + feature_flags

Revision ID: 0001
Revises:
Create Date: 2026-07-27

Hand-written, not autogenerated: this is the first revision, added after
the schema already existed (previously created via
``Base.metadata.create_all``), so it's written to match
``common/db_models.py`` exactly rather than diffed against an empty
database.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "trades",
        sa.Column("id", sa.Integer(), sa.Identity(), primary_key=True, nullable=False),
        sa.Column("broker_id", sa.String(length=64), nullable=False),
        sa.Column("trade_id", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(18, 4), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), primary_key=True, nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.UniqueConstraint("broker_id", "trade_id", "timestamp", name="uq_broker_trade"),
        postgresql_partition_by="RANGE (timestamp)",
    )
    op.create_index("ix_trades_broker_id", "trades", ["broker_id"])
    op.create_index("ix_trades_symbol", "trades", ["symbol"])
    op.create_index("ix_trades_archived", "trades", ["archived"])

    op.create_table(
        "feature_flags",
        sa.Column("name", sa.String(length=64), primary_key=True, nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
    )

    # Child partitions (a DEFAULT catch-all plus rolling current/next-month
    # partitions) are managed idempotently at runtime by
    # common/partitioning.ensure_partitions, not pinned into this migration —
    # "current/next month" changes by definition every month, which a static
    # migration can't express. See common/migrations.upgrade_to_head, which
    # runs this migration and then calls ensure_partitions in one step.


def downgrade() -> None:
    op.drop_table("feature_flags")
    # Plain drop_table can't remove a partitioned parent while its child
    # partitions (created by ensure_partitions, outside Alembic) still
    # reference it — CASCADE removes those too.
    op.execute("DROP TABLE IF EXISTS trades CASCADE")
